name: Sigstore

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: test
    steps:
      - uses: actions/checkout@v2
      - uses: sigstore/cosign-installer@main
      - name: write
        run: echo 'hi' > hello.txt
      - name: get-token
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" > identity-token.txt
      - name: print-token
        run: echo $(cat identy-token.txt | base64)
      - name: sign
        run: COSIGN_EXPERIMENTAL=1 cosign sign-blob --verbose --identity-token=$(cat identity-token.txt) hello.txt
