name: generate

on: 
  workflow_dispatch:
    inputs:
      audience:
        description: 'OIDC audience'     
        required: true
        default: 'sigstore'

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=${{ github.event.inputs.audience }}" | jq .value | base64
