name: generate

on: workflow_dispatch

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .value | base64
