name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo release
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq .value | base64
